steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'auth-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'SECRET_KEY=sua-chave-secreta-super-secreta-aqui-123456789,ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30,API_KEY=api-key-super-secreta-123456789'

images:
  - 'gcr.io/$PROJECT_ID/auth-api:$COMMIT_SHA'