steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/analytics-clientco/auth-api-clientco:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/analytics-clientco/auth-api-clientco:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'auth-api-clientco'
    - '--image'
    - 'gcr.io/analytics-clientco/auth-api-clientco:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--set-env-vars'
    - 'SECRET_KEY=analytics-clientco-jwt-secret-key-2025-super-forte-aicube-ca,ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30,API_KEY=analytics-clientco-api-key-2025-bramos-aicube-ca-production'

images:
  - 'gcr.io/analytics-clientco/auth-api-clientco:$COMMIT_SHA'